### ISSUE TITLE
Issue with PSR-16 implementation

### ISSUE THREAD

**Issue by Viliasas** [paillechat/apcu-simple-cache#3]
Hello,

We're using "apcu-simple-cache" with PhpSpreadsheet (https://github.com/PHPOffice/PhpSpreadsheet) and we're getting this error:

`Fatal error: Uncaught TypeError: Argument 1 passed to Paillechat\ApcuSimpleCache\ApcuCache::assertKeyNames() must be of the type array, object given, called in /var/www/orders/vendor/paillechat/apcu-simple-cache/src/ApcuCache.php on line 124 and defined in /var/www/orders/vendor/paillechat/apcu-simple-cache/src/ApcuCache.php:183 Stack trace: #0 /var/www/orders/vendor/paillechat/apcu-simple-cache/src/ApcuCache.php(124): Paillechat\ApcuSimpleCache\ApcuCache->assertKeyNames(Object(Generator)) #1 /var/www/orders/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Collection/Cells.php(492): Paillechat\ApcuSimpleCache\ApcuCache->deleteMultiple(Object(Generator)) #2 /var/www/orders/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Collection/Cells.php(479): PhpOffice\PhpSpreadsheet\Collection\Cells->__destruct() #3 /var/www/orders/vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Worksheet/Worksheet.php(385): PhpOffice\PhpSpreadsheet\Collection\Cells->unsetWorksheetCells() #4 /var/www/orders/vendor/phpoffice/phpspreadsheet/src/ in /var/www/orders/vendor/paillechat/apcu-simple-cache/src/ApcuCache.php on line 183`

When checking PhpSpreadsheet issues, I've noticed that according PSR-16 keys should be iterable and not only arrays (https://github.com/PHPOffice/PhpSpreadsheet/issues/1049).

Could this be fixed in "apcu-simple-cache"?

**Comment by Viliasas** [comment]
Created a pull request https://github.com/paillechat/apcu-simple-cache/pull/4 for this. If anything is wrong in it, just tell me and I will change it.
